### ISSUE TITLE
SDK Obj-C headers lack Swift annotations

### ISSUE THREAD

**Issue by PatInANutshell** [TuneOSS/sdk-release#30] opened 2017-03-27 18:25 UTC
Xcode will treat the lack of annotations as implicitly unwrapped optionals, which will cause exceptions if you pass in nil, which in many cases is a valid value for properties or arguments. It also forces calls to treat new instances as optional when they don't need to be.

**Comment by hasaudrey** [comment] 2017-03-29 17:32
I think this is a dupe of https://github.com/TuneOSS/sdk-release/issues/27, or at least I hope to solve them both at the same time

**Closed** 2017-03-29 17:35 UTC
Labels: duplicate
